### ISSUE TITLE
Implementing maybe  support for Lists

### ISSUE THREAD

**Issue by swnck** [rahul-acr/easy-dto-core#6]
It would be cool if we could implement the following: List<Entity> entity = new ArrayList<>();. For example, I have a UserEntity with this property:

```
@DtoProperty(profile="SESSION")
List<Session> sessions = new ArrayList<>();
```
And in the session entity, I have a DTO property:
```
@DtoProperty(profile="SESSION")
public UUID sessionId;
```

Because when I get this with the Spring REST API, it looks like this:

`"sessions": {}`

**Comment by rahul-acr** [comment]
@swnck were you able to resolve the issue?

**Comment by swnck** [comment]
Yes, I have forked this repo at my organization with worked List
